### ISSUE TITLE
Minimize duplication for unsupported platforms

### ISSUE THREAD

**Issue by jdm** [servo/devices#8]
Most of the methods on BluetoothAdapter call `self.get_adapter()` in the Linux implementation. This means that if we made `get_adapter()` return a `Result` value, most of the caller methods could use `Result::map` and not require two different implementations. Similar tricks should be possible for the other types as well.

**Comment by mrmiywj** [comment]
Hi, maybe I can try this.

**Comment by jdm** [comment]
@mrmiywj Please do! Ask questions if anything is confusing :)

**Comment by mrmiywj** [comment]
Hmm. Actually the issue is that methods like `self.get_adapter()` will return a `Result` type value, which is  `Ok(_)` on linux and `Err(_)` on other platform. Now we implement functions separately on linux and other platform, since only linux supported now. But actually a `Result::map` could solve this issue. 
Did I understand it correctly?

**Comment by jdm** [comment]
Yes.

**Comment by dati91** [comment]
I think this issue is a little bit outdated. Maybe we should close it?

**Comment by jdm** [comment]
Yes, my ideas didn't work.
